/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joas_utils_WatchDogTimer */

#ifndef _Included_com_joas_utils_WatchDogTimer
#define _Included_com_joas_utils_WatchDogTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joas_utils_WatchDogTimer
 * Method:    open
 * Signature: (I)V
 */
JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_open
(JNIEnv
*, jobject, jint);

/*
 * Class:     com_joas_utils_WatchDogTimer
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_start
(JNIEnv
*, jobject);

/*
 * Class:     com_joas_utils_WatchDogTimer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_stop
(JNIEnv
*, jobject);

/*
 * Class:     com_joas_utils_WatchDogTimer
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_update
(JNIEnv
*, jobject);

/*
 * Class:     com_joas_utils_WatchDogTimer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_close
(JNIEnv
*, jobject);


JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_hdmiOn
(JNIEnv
*, jobject);

JNIEXPORT void JNICALL
Java_com_joas_utils_WatchDogTimer_hdmiOff
(JNIEnv
*, jobject);


#ifdef __cplusplus
}
#endif
#endif
